{{- if and (eq .Values.credentials.enable true) (eq .Values.credentials.type "ExternalSecret") -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.credentials.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.credentials.externalSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ include "name" . }}
  refreshInterval: 1m
  target:
    name: {{ include "name" . }}
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        {{- with .Values.credentials.externalSecret.target.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.credentials.externalSecret.target.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      data:
      {{- with .Values.credentials.externalSecret.target.data }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- range .Values.credentials.externalSecret.secret }}
        {{ .secretKey }}: "{{ printf "{{ .%s }}" .secretKey }}"
      {{- end }}
  data:
  {{- with .Values.credentials.externalSecret.secret }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
