{{- if and (eq .Values.credentials.enable true) (eq .Values.credentials.type "Secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.credentials.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.credentials.secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $value := .Values.credentials.secret.data }}
  {{ $key }}: {{ $value | b64enc -}}
{{- end }}
{{- end -}}
