{{- if and (eq .Values.credentials.enable true) (eq .Values.credentials.type "ExternalSecret") -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.credentials.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.credentials.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
  {{- if eq .Values.credentials.secretStore.provider.type "aws" }}
    aws:
      service: {{ .Values.credentials.secretStore.provider.aws.service }}
      region: {{ .Values.credentials.secretStore.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "name" . }}
  {{- end }}
  {{- if eq .Values.credentials.secretStore.provider.type "azure" }}
    azurekv:
      authType: WorkloadIdentity
      environmentType: {{ .Values.credentials.secretStore.provider.azure.environmentType }}
      vaultUrl: {{ .Values.credentials.secretStore.provider.azure.vaultUrl }}
      serviceAccountRef:
        name: {{ include "name" . }}
  {{- end }}
{{- end -}}
