{{- if and (eq .Values.credentials.enable true) (eq .Values.credentials.type "ExternalSecret") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.credentials.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.credentials.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
